// === MUSIC TRACKS DATA ===
// This file contains all your music tracks - easy to find and edit!

const musicData = [
    {
        id: 1,
        title: "Palagi Ko Lang Gagalingan",
        artist: "Ace Flow",
        genre: ["Hip-Hop", "Trap"],
        image: "assets/images/music-covers/Cover1.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2024-01-15",
        featured: true,
        plays: 125000,
        duration: "3:45"
    },
    {
        id: 2,
        title: "Manifest",
        artist: "Ace Flow, J-Phil, J-Karl, MC Kram, Shadyboi",
        genre: ["Hip-Hop", "Rap"],
        image: "assets/images/music-covers/Cover2.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2024-01-10",
        featured: true,
        plays: 98000,
        duration: "2:58"
    },
    {
        id: 3,
        title: "Space Cake",
        artist: "SAJKA",
        genre: ["Brazillian Funk", "Jersey Club"],
        image: "assets/images/music-covers/Space Cake.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://www.youtube.com/watch?v=Z4LVd1u30pg",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2024-01-05",
        featured: true,
        plays: 150000,
        duration: "3:12"
    },
    {
        id: 4,
        title: "Kumbaga",
        artist: "SAJKA ft. Manta",
        genre: ["Neo-Soul", "Reggae"],
        image: "assets/images/music-covers/Cover4.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-12-20",
        featured: true,
        plays: 120000,
        duration: "4:02"
    },
    {
        id: 5,
        title: "Catnip",
        artist: "SAJKA ft. Manta",
        genre: ["Hip-Hop", "New Jazz"],
        image: "assets/images/music-covers/Cover5.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-12-15",
        featured: false,
        plays: 85000,
        duration: "3:28"
    },
    {
        id: 6,
        title: "Boss II Men",
        artist: "JRWN ft. MANTA & SAJKA",
        genre: ["Hip-Hop", "Trap"],
        image: "assets/images/music-covers/Cover6.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-12-10",
        featured: false,
        plays: 92000,
        duration: "3:15"
    },
    {
        id: 7,
        title: "BASANGBASA",
        artist: "Manta ft. SAJKA",
        genre: ["Hip-Hop", "Reggae"],
        image: "assets/images/music-covers/Cover7.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-12-05",
        featured: false,
        plays: 68000,
        duration: "2:45"
    },
    {
        id: 8,
        title: "IDK",
        artist: "JRWN ft. SAJKA",
        genre: ["Hip-Hop", "R&B"],
        image: "assets/images/music-covers/Cover8.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-11-30",
        featured: false,
        plays: 110000,
        duration: "3:20"
    },
    {
        id: 9,
        title: "Masyadong Boring",
        artist: "Bxbydos ft. JOM",
        genre: ["Hip-Hop", "Drill"],
        image: "assets/images/music-covers/Cover9.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-11-25",
        featured: false,
        plays: 78000,
        duration: "4:10"
    },
    {
        id: 10,
        title: "SIGE",
        artist: "JHOM P ft. SAJKA",
        genre: ["Hip-Hop", "Trap"],
        image: "assets/images/music-covers/Cover10.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-11-20",
        featured: false,
        plays: 95000,
        duration: "3:35"
    },
    {
        id: 11,
        title: "My Everything",
        artist: "J-Karl ft. Edd Azer",
        genre: ["R&B", "Neo-Soul"],
        image: "assets/images/music-covers/Cover1.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-11-15",
        featured: false,
        plays: 87000,
        duration: "3:45"
    },
    {
        id: 12,
        title: "NAGPAPARINIG",
        artist: "Douffie ft. Naino",
        genre: ["Hip-Hop", "Jersey Club"],
        image: "assets/images/music-covers/Cover2.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-11-10",
        featured: false,
        plays: 76000,
        duration: "3:20"
    },
    {
        id: 13,
        title: "Amiga",
        artist: "GL4DDYY, Raya Nindale",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover3.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-11-05",
        featured: false,
        plays: 82000,
        duration: "3:10"
    },
    {
        id: 14,
        title: "STU FREESTYLE",
        artist: "Yo D333zy ft. Jeko Royo, Jr Crown, Manta",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover4.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-10-30",
        featured: false,
        plays: 94000,
        duration: "4:15"
    },
    {
        id: 15,
        title: "Sige Lang",
        artist: "Micosuabe ft. Teys",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover5.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-10-25",
        featured: false,
        plays: 71000,
        duration: "3:30"
    },
    {
        id: 16,
        title: "RESET",
        artist: "RUSLIE CLEAR, MRCO",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover6.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-10-20",
        featured: false,
        plays: 68000,
        duration: "3:45"
    },
    {
        id: 17,
        title: "Romano Tribute Song",
        artist: "J-King ft. Lil-P",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover7.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-10-15",
        featured: false,
        plays: 89000,
        duration: "4:00"
    },
    {
        id: 18,
        title: "Di Na Sana",
        artist: "Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover8.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-10-10",
        featured: false,
        plays: 105000,
        duration: "3:25"
    },
    {
        id: 19,
        title: "Gusto Mo ng Patago (G.M.N.P Drill Remix)",
        artist: "Wally Wavy",
        genre: ["Drill"],
        image: "assets/images/music-covers/Cover9.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-10-05",
        featured: false,
        plays: 92000,
        duration: "3:15"
    },
    {
        id: 20,
        title: "LDR (Missing You Karong Pasko)",
        artist: "GL4DDYY ft. Dizzy Mike",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover10.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-09-30",
        featured: false,
        plays: 78000,
        duration: "3:50"
    },
    {
        id: 21,
        title: "Ikaw Parin",
        artist: "Scota WRLD",
        genre: ["R&B"],
        image: "assets/images/music-covers/Cover1.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-09-25",
        featured: false,
        plays: 86000,
        duration: "3:40"
    },
    {
        id: 22,
        title: "Hiling Kay Santa",
        artist: "XRP Music ft. Eidref",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover2.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-09-20",
        featured: false,
        plays: 73000,
        duration: "3:20"
    },
    {
        id: 23,
        title: "Chance",
        artist: "J-Karl",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover3.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-09-15",
        featured: false,
        plays: 91000,
        duration: "3:35"
    },
    {
        id: 24,
        title: "MY PARTY",
        artist: "Cry Kiddo ft. RystaQuiva, Edd Azer, Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover4.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-09-10",
        featured: false,
        plays: 88000,
        duration: "4:10"
    },
    {
        id: 25,
        title: "Aking Ama",
        artist: "Ragidd, Ace Flow, SixTone",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover5.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-09-05",
        featured: false,
        plays: 95000,
        duration: "3:55"
    },
    {
        id: 26,
        title: "I'm Done",
        artist: "GL4DDYY",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover6.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-08-30",
        featured: false,
        plays: 82000,
        duration: "3:25"
    },
    {
        id: 27,
        title: "Ride Wit Me",
        artist: "Santi 1Hunnit",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover7.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-08-25",
        featured: false,
        plays: 76000,
        duration: "3:15"
    },
    {
        id: 28,
        title: "Pera At Ea",
        artist: "Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover8.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-08-20",
        featured: false,
        plays: 89000,
        duration: "3:30"
    },
    {
        id: 29,
        title: "Hood Playa",
        artist: "Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover9.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-08-15",
        featured: false,
        plays: 94000,
        duration: "3:40"
    },
    {
        id: 30,
        title: "OTW2RICHES",
        artist: "Ace Flow ft. Shadyboi, SixTone",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover10.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-08-10",
        featured: false,
        plays: 107000,
        duration: "4:05"
    },
    {
        id: 31,
        title: "Palagi Ko Lang Gagalingan, Pt.2",
        artist: "Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover1.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-08-05",
        featured: false,
        plays: 112000,
        duration: "3:50"
    },
    {
        id: 32,
        title: "Million Dreams",
        artist: "Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover2.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-07-30",
        featured: false,
        plays: 98000,
        duration: "3:35"
    },
    {
        id: 33,
        title: "When The Sun Goes Down",
        artist: "Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover3.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-07-25",
        featured: false,
        plays: 85000,
        duration: "3:45"
    },
    {
        id: 34,
        title: "LANDMINE",
        artist: "Manta ft. Øff Suel",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover4.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-07-20",
        featured: false,
        plays: 92000,
        duration: "3:20"
    },
    {
        id: 35,
        title: "DAMN!",
        artist: "Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover5.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-07-15",
        featured: false,
        plays: 101000,
        duration: "3:10"
    },
    {
        id: 36,
        title: "Ngayon Manigas Ka",
        artist: "D'SOUTH",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover6.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-07-10",
        featured: false,
        plays: 88000,
        duration: "3:25"
    },
    {
        id: 37,
        title: "Naaalala Kita",
        artist: "D'SOUTH",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover7.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-07-05",
        featured: false,
        plays: 79000,
        duration: "3:40"
    },
    {
        id: 38,
        title: "Last Time",
        artist: "GL4DDYY",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover8.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-06-30",
        featured: false,
        plays: 86000,
        duration: "3:30"
    },
    {
        id: 39,
        title: "Moon Walk",
        artist: "Crown One",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover9.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-06-25",
        featured: false,
        plays: 74000,
        duration: "3:15"
    },
    {
        id: 40,
        title: "Laging Ikaw",
        artist: "Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover10.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-06-20",
        featured: false,
        plays: 91000,
        duration: "3:50"
    },
    {
        id: 41,
        title: "BITUIN",
        artist: "MC Kram, J-Karl, Shady",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover1.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-06-15",
        featured: false,
        plays: 97000,
        duration: "4:00"
    },
    {
        id: 42,
        title: "Bago",
        artist: "SixTone ft. Ace Flow",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover2.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-06-10",
        featured: false,
        plays: 83000,
        duration: "3:35"
    },
    {
        id: 43,
        title: "ICY",
        artist: "YSU",
        genre: ["Hip-Hop"],
        image: "assets/images/music-covers/Cover3.jpg",
        gifPreview: "assets/images/previews/Space Cake.gif",
        youtubeLink: "https://youtube.com/watch?v=YOUR_VIDEO_ID",
        spotifyLink: "https://open.spotify.com/track/YOUR_TRACK_ID",
        releaseDate: "2023-06-05",
        featured: false,
        plays: 75000,
        duration: "3:20"
    }
];

// Export for use in other files
if (typeof module !== 'undefined' && module.exports) {
    module.exports = musicData;
}
